.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" vanessa_gethostbyname.1                                December 2008
.\" Simon Horman                                      horms@verge.net.au
.\"
.\" vanessa_gethostbyname
.\" Expose libc's gethostbyname to userspace using libvanessa_socket
.\" Copyright (C) 1999-2008  Simon Horman <horms@verge.net.au>
.\" 
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of the
.\" License, or (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
.\" 02111-1307  USA
.\"
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH VANESSA_GETHOSTBYNAME 1 "2nd December 2005"
.SH NAME
vanessa_gethostbyname \- expose libc's gethostbyname to userspace
.SH SYNOPSIS
\fBvanessa_gethostbyname\fP [OPTIONS] HOST
.SH DESCRIPTION

Resolve a given hostname using libc's gethostbyname
.TP
.B -h|--help:
Display help information and exit.
.TP
.B -v|--version:
Display version information and exit.
.SH AUTHOR
Simon Horman <horms@verge.net.au>
